name: wakaranai
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  equatable: 2.0.3
  json_serializable: ^6.3.1
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  json_annotation: ^4.6.0
  transparent_image: 2.0.0
  intl: 0.17.0
  photo_view: ^0.14.0
  cached_network_image: ^3.2.1
  flutter_cache_manager: 3.3.0
  shared_preferences: ^2.0.15
  flutter_settings_ui: 2.0.1
  adaptive_dialog: ^1.6.4+2
  shimmer: ^2.0.0
  wakascript:
    path: ../wakascript
  flutter_svg: ^1.1.1+1
  pull_to_refresh: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.9.3


flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  retrofit_generator: ^4.0.2

flutter:

  uses-material-design: true

  assets:
    - .env

