name: wakaranai
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  wakascript:
    path: ../wakascript

  path: ^1.8.2
  path_provider: ^2.0.12
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  json_serializable: ^6.6.1
  retrofit: ^3.3.1
  dio: ^4.0.6
  json_annotation: ^4.8.0
  transparent_image: 2.0.0
  intl: ^0.17.0
  intl_utils: ^2.8.1
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: 3.3.0
  adaptive_dialog: ^1.8.2
  flutter_svg: ^2.0.0+1
  pull_to_refresh: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.11.0
  another_xlider: ^1.1.2
  transparent_pointer: ^1.0.0
  visibility_detector: ^0.3.3
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.17
  flutter_inappwebview: ^5.7.2+3
  flutter_secure_storage: ^8.0.0
  flutter_isolate: ^2.0.4
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.12


flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"

#dependency_overrides:
#  analyzer: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  retrofit_generator: ^4.2.0
  drift_dev: ^2.5.2

flutter:

  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Ubuntu mono
      fonts:
        - asset: fonts/Ubuntu-B.ttf
        - asset: fonts/Ubuntu-C.ttf
        - asset: fonts/Ubuntu-L.ttf
        - asset: fonts/Ubuntu-M.ttf
        - asset: fonts/Ubuntu-R.ttf
        - asset: fonts/Ubuntu-Th.ttf
        - asset: fonts/UbuntuMono-B.ttf
        - asset: fonts/UbuntuMono-R.ttf

